<?php

namespace LeBonCoinDesServices\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * departementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class departementsRepository extends EntityRepository
{
}
