<?php

namespace LeBonCoinDesServices\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * regionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class regionsRepository extends EntityRepository
{
}
